### ISSUE TITLE
duplicate access logic between route and template policies

### ISSUE THREAD

**Issue by jpaas** [wildland/ember-sanctify#9]
A typical pattern as described in the readme is:

```
{{#if (can-access 'post' 'create')}}
  {{#link-to 'posts.new'}}New Post{{/link-to}}
{{else}}
  Please {{#link-to 'login'}}log in{{/link-to}} to create a new post.
{{/if}}
```

But in order to enforce this I have to implement canCreate in `policys/post.js` and canAccess in `policys/posts/new.js`. The logic for both is the typically going to be the same. Is there any way we could DRY this up?

**Comment by Samsinite** [comment]
A common pattern I've done is just to put the access logic into a function and called it from both. The policy object is really just an object so your options here are completely open and up to you.

A contrived example of say `policys/post.js`:

``` js
import Ember from 'ember';
import inject from 'ember-cli-injection/inject';

var injectTorii = inject('torii');

export function checkUserAccess(user) {
  // return true/false or promise that returns true/false here
}

export default Ember.Object.extend({
  session:  injectTorii('session'), /*uses ember-cli-injection to inject 'torii:session' */

  canAccess: function(/*route, model*/) {
    var user = this.get('session.currentUser');

    return checkUserAccess(user);
  },

  canCreate: function(obj) {
     var user = this.get('session.currentUser');

    return checkUserAccess(user);
  }
});
```

Hope this makes sense and helps. If you have any code examples too, feel free to post (or email if you don't want to share on github) and I'll do my best to help you out.

**Comment by Samsinite** [comment]
Since I exported the function above, you can then import it into another policy to use:

say this is 'policys/posts/new.js`

``` js
import { checkUserAccess } from '../post';
```

**Comment by Samsinite** [comment]
Also, the policy is looked up from the container/resolver (https://github.com/wildland/ember-sanctify/blob/master/addon/helpers/can-access.js#L25) based off of the string from the first param you pass to it. So you can call whatever policy you'd like inside your template using the helper and also call whatever method you want as long as it starts with `can`

**Comment by jpaas** [comment]
I ended up using your last suggestion to direct my can-access helpers at my route's canAccess policies. Thanks!

**Comment by Samsinite** [comment]
No problem, glad I could help :)
